Data model Project : Predict survival of patients with heart failure

1.import package

```{r}
library(tidyverse)
library(caret)
library(lift)
library(ROCR)
library(rpart)
library(rpart.plot)
library(readr)
set.seed(69)
```

```{r}
heart_failure_clinical_records_dataset <- read_csv("heart_failure_dataset.csv")
heart_failure_clinical_records_dataset
```

Time can not use to predict

```{r}
dataset <- select(dataset,c(-time))

```

```{r}
dataset
```

```{r}
any(is.na(heart_failure_clinical_records_dataset))
```

```{r}
heart_failure_clinical_records_dataset %>% rename(
    cpk = creatinine_phosphokinase,
    death = DEATH_EVENT
  ) %>% 
  select(-time) -> all_data
```

```{r}
all_data$death = as.factor(all_data$death)
```

```{r}
#Check Data Type 
unique(all_data$age)        #Continuous
unique(all_data$anaemia)    #Categorical
unique(all_data$cpk)        #Continuous
unique(all_data$diabetes)   #Categorical
unique(all_data$ejection_fraction)   #Continuous
unique(all_data$high_blood_pressure) #Categorical
unique(all_data$platelets)           #Continuous 
unique(all_data$serum_creatinine)    #Continuous 
unique(all_data$serum_sodium)        #Continuous
unique(all_data$sex)     #Categorical
unique(all_data$smoking) #Categorical 
unique(all_data$death)   #Response y is Categorical
```

```{r}
all_data
```
